---

- name: Setup watchtower to automatically update docker image
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    state: started
    # recreate: yes
    restart_policy: unless-stopped
    env:
      WATCHTOWER_SCHEDULE: "0 */30 * * * *"
      HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      NO_PROXY: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock