---

- name: This empty request is to avoid an error message when finishing the cluster setup
  uri:
    url: http://{{inventory_hostname}}:5984/
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    force_basic_auth: yes
    method: GET
    status_code:
      - '200'
      - '201'
  when: inventory_hostname in groups['db_head']

- name: Finish cluster setup
  uri:
    url: http://{{inventory_hostname}}:5984/_cluster_setup
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    force_basic_auth: yes
    method: POST
    body_format: json
    body:
      action: finish_cluster
    status_code:
      - '200'
      - '201'
  when: inventory_hostname in groups['db_head']

- name: Add twitter database
  uri:
    url: http://{{inventory_hostname}}:5984/twitter?partitioned=true
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    force_basic_auth: yes
    method: PUT
    status_code:
      - '200'
      - '201'
  when: inventory_hostname in groups['db_head']

