---

- name: This empty request is to avoid an error message when finishing the cluster setup
  uri:
    url: http://{{inventory_hostname}}:5984/
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    method: GET
  when: inventory_hostname in groups['db_head']

- name: Finish cluster setup
  uri:
    url: http://{{inventory_hostname}}:5984/_cluster_setup
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
    body:
      action: finish_cluster
  when: inventory_hostname in groups['db_head']

- name: Add twitter database
  uri:
    url: http://{{inventory_hostname}}:5984/twitter
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    method: PUT
  when: inventory_hostname in groups['db_head']

