---

- name: Basic setup
  hosts:
  - db_head
  - db_workers
  - webservices

  vars_files:
  - host_vars/app.yaml

  gather_facts: true
  remote_user: ec2-user
  become: true

  roles:
  - common
  - setup-docker

- name: Setup couchDB
  hosts:
  - db_head
  - db_workers

  vars_files:
  - host_vars/app.yaml

  gather_facts: true
  remote_user: ec2-user
  become: true

  roles:
  - name: setup-db-volumn
    tags: ['couchdb']
  - name: setup-couchdb
    tags: ['couchdb']
  - name: setup-couchdb-head
    tags: ['couchdb']

- name: Setup redis
  hosts:
  - webservices

  gather_facts: true
  remote_user: ec2-user
  become: true

  roles:
  - name: setup-redis
    tags: ['redis']

- name: Setup application
  hosts:
  - webservices

  vars_files:
  - host_vars/app.yaml

  gather_facts: true
  remote_user: ec2-user
  become: true

  roles:
  - name: setup-backend
    tags: ['app']

- name: Setup harvester
  hosts:
  - db_head
  - db_workers

  vars_files:
  - host_vars/app.yaml

  gather_facts: true
  remote_user: ec2-user
  become: true

  roles:
  - name: setup-harvester
    tags: ['harvester']