---

- name: Add utils about adding a repository
  yum:
    name: ['yum-utils']
    state: present

- name: Add docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  register: repo_setup_return

# - name: Print repo setup log
#   debug:
#     var: repo_setup_return

- name: Install docker
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: Creates directory for docker config
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: true

- name: 'Setup docker config file'
  copy:
    src: http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf

- name: Start docker
  systemd:
    name: docker
    state: started
    enabled: true