---

- name: Add utils about adding a repository
  yum:
    name: ['yum-utils']
    state: present
  become: yes

- name: Add docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  register: repo_setup_return
  become: yes

- name: Print repo setup log
  debug:
    var: repo_setup_return

- name: Install docker
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
  become: yes

- name: Start docker
  systemd:
    name: docker
    state: started
  become: yes