---

- name: Ensure model folder exist
  file: path={{harvester.model_path}} state=directory

- name: Install gdown
  pip:
    name: ['gdown']
    state: latest

- name: Check that the model file exists
  stat:
    path: "{{harvester.model_path}}{{harvester.model_name}}"
  register: stat_result

- name: Download model
  shell: "python3 -m gdown.cli '{{harvester.model_url}}' -O '{{harvester.model_path}}{{harvester.model_name}}'"
  when: not stat_result.stat.exists

- name: Deploy harvester
  docker_container:
    name: harvester
    image: "{{harvester.image}}"
    pull: true # always use the latest image
    state: started
    # recreate: yes
    restart_policy: unless-stopped
    env:
      COUCHDB_HOST: "{{groups.db_head[0]}}"
      COUCHDB_USERNAME: '{{couchdb.user}}'
      COUCHDB_PASSWORD: '{{couchdb.pwd}}'
      REDIS_HOST: "{{groups.webservices[0]}}"
      HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      NO_PROXY: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au
    volumes:
    - "{{harvester.model_path}}{{harvester.model_name}}:/opt/bert.model"