---

- name: Ensure model folder exist
  file: path={{harvester.model_path}} state=directory

- name: Install gdown
  pip:
    name: ['gdown']
    state: latest

- name: Check that the model file exists
  stat:
    path: "{{harvester.model_path}}{{harvester.model_name}}"
  register: stat_result

- name: Download model
  shell: "python3 -m gdown.cli '{{harvester.model_url}}' -O '{{harvester.model_path}}{{harvester.model_name}}'"
  when: not stat_result.stat.exists

- name: Deploy harvester
  docker_container:
    name: harvester
    image: "{{harvester.image}}"
    pull: true # always use the latest image
    state: started
    # recreate: yes
    restart_policy: unless-stopped
    network_mode: host
    env:
      COUCHDB_HOST: "{{groups.db_head[0]}}"
      COUCHDB_USER: '{{couchdb.user}}'
      COUCHDB_PASSWORD: '{{couchdb.pwd}}'
      REDIS_HOST: "{{groups.webservices[0]}}"
    volumes:
    - "{{harvester.model_path}}{{harvester.model_name}}:/opt/bert.model"