# Common vars
availability_zone: melbourne-qh2-uom

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "Security group for CouchDB Cluster"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: redis
    description: "Security group for Redis"
    protocol: tcp
    port_range_min: 6379
    port_range_max: 6379
    remote_ip_prefix: 0.0.0.0/0

instances:
  - name: db-1
    security_groups: 
    - default
    - ssh
    - couchdb
    flavor: uom.mse.2c9g
  - name: db-2
    security_groups:
    - default
    - ssh
    - couchdb
    flavor: uom.mse.2c9g
  - name: db-3
    security_groups:
    - default
    - ssh
    - couchdb
    flavor: uom.mse.2c9g
  - name: webservice
    security_groups:
    - default
    - ssh
    - http
    - redis
    # flavor: m3.small  # seems like that this kind of instance does not have enough capacity
    flavor: uom.mse.1c4g

instance_image: '9a689870-7c2b-4c74-a9a8-44f9ff587b43' # CentOS 8 x86_64
instance_key_name: 'My key' # Specify your key name here

# Volume
volumes:
- vol_name: db-vol-1
  vol_size: 150
  instance: db-1
- vol_name: db-vol-2
  vol_size: 150
  instance: db-2
- vol_name: db-vol-3
  vol_size: 150
  instance: db-3
# - vol_name: service-vol-3
#   vol_size: 10