---

- name: Set an alias of host ip
  set_fact:
    host_ip: '{{hostvars[inventory_hostname].ansible_default_ipv4.address}}'
    head_node_ip: '{{groups.db_head[0]}}'
    node_count: "{{groups['db_workers'] | length + 1}}"

- name: Create CouchDB container
  docker_container:
    name: couchdb
    image: ibmcom/couchdb3:{{couchdb.version}}
    state: present
    recreate: yes
    env:
      COUCHDB_USER: '{{couchdb.user}}'
      COUCHDB_PASSWORD: '{{couchdb.pwd}}'
      COUCHDB_SECRET: '{{couchdb.secret}}'
      ERL_FLAGS: '-setcookie {{couchdb.secret}} -name couchdb@{{host_ip}}'
    # just map all ports to server because I don't want to waste time on it anymore
    network_mode: host
    volumes:
    - /mnt/data/couchdb:/opt/couchdb/data

- name: 'Setup systemd file'
  copy:
    src: couchdb.service
    dest: /etc/systemd/system/couchdb.service
    mode: u=rw,g=r,o=r

- name: Start couchdb
  systemd:
    name: couchdb
    state: started
    daemon_reload: true
    enabled: true

- name: Setup cluster for CouchDB worker nodes
  uri:
    url: http://{{head_node_ip}}:5984/_cluster_setup
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    force_basic_auth: yes
    method: POST
    body_format: json
    body:
      action: enable_cluster
      bind_address: '0.0.0.0'
      username: '{{couchdb.user}}'
      password: '{{couchdb.pwd}}'
      port: '5984'
      remote_node: '{{host_ip}}'
      node_count: '{{node_count}}'
      remote_current_user: '{{couchdb.user}}'
      remote_current_password: '{{couchdb.pwd}}'
    status_code:
      - '200'
      - '201'   # <- It does not automatically recognize 2XX codes.
  when: inventory_hostname in groups['db_workers']

- name: Initialize CouchDB worker nodes
  uri:
    url: http://{{head_node_ip}}:5984/_cluster_setup
    url_username: '{{couchdb.user}}'
    url_password: '{{couchdb.pwd}}'
    force_basic_auth: yes
    method: POST
    body_format: json
    body:
      action: add_node
      host: '{{host_ip}}'
      username: '{{couchdb.user}}'
      password: '{{couchdb.pwd}}'
      port: '5984'
    status_code:
      - '200'
      - '201'
  when: inventory_hostname in groups['db_workers']
      